AdminProductRequest:
  type: object
  required: [name, nameAr, price, stock]
  properties:
    name:
      type: string
    nameAr:
      type: string
    description:
      type: string
      nullable: true
    descriptionAr:
      type: string
      nullable: true
    images:
      type: array
      items:
        type: string
      description: Array of image URLs
    price:
      type: number
      format: float
    priceBeforeDiscount:
      type: number
      format: float
      nullable: true
    discount:
      type: number
      format: float
      nullable: true
    stock:
      type: integer
    category:
      type: string
      nullable: true
    isFeatured:
      type: boolean
      default: false
