ChildWithAssessments:
  allOf:
    - $ref: "#/components/schemas/Child"
    - type: object
      properties:
        assessmentResults:
          type: array
          items:
            type: object
            properties:
              id:
                type: string
              testId:
                type: string
                nullable: true
              questionId:
                type: string
                nullable: true
              scoreGiven:
                type: integer
                nullable: true
              totalScore:
                type: integer
                nullable: true
              maxScore:
                type: integer
                nullable: true
              sessionId:
                type: string
                nullable: true
              timestamp:
                type: string
                format: date-time
              test:
                $ref: "#/components/schemas/AssessmentTest"
              helpAssessment:
                allOf:
                  - $ref: "#/components/schemas/HelpAssessment"
                nullable: true
              question:
                type: object
                nullable: true
                properties:
                  id:
                    type: string
                  testId:
                    type: string
                  maxScore:
                    type: integer
                    nullable: true
              qCarsAnswers:
                type: array
                items:
                  $ref: "#/components/schemas/AssessmentAnswerCars"
              qAnalogyAnswers:
                type: array
                items:
                  $ref: "#/components/schemas/AssessmentAnswerAnalogy"
              qVisualMemoryAnswers:
                type: array
                items:
                  $ref: "#/components/schemas/AssessmentAnswerVisualMemory"
              qAuditoryMemoryAnswers:
                type: array
                items:
                  $ref: "#/components/schemas/AssessmentAnswerAuditoryMemory"
        helpAssessments:
          type: array
          items:
            allOf:
              - $ref: "#/components/schemas/HelpAssessment"
              - type: object
                properties:
                  doctor:
                    type: object
                    nullable: true
                    properties:
                      id:
                        type: string
                      name:
                        type: string
                      email:
                        type: string
                        format: email
                  assessmentResult:
                    allOf:
                      - $ref: "#/components/schemas/AssessmentResult"
                    nullable: true
