AdminProfile:
  type: object
  properties:
    id:
      type: string
      format: uuid
    name:
      type: string
    email:
      type: string
      format: email
    role:
      type: string
      enum: [SUPER_ADMIN, ADMIN, MODERATOR, SUPPORT]
    isActive:
      type: boolean
    createdAt:
      type: string
      format: date-time

AdminAuthResponse:
  type: object
  properties:
    admin:
      $ref: "#/components/schemas/AdminProfile"
    token:
      type: string
      example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
