import express from 'express';
import authRoutes from './admin/auth.routes.js';
import dashboardRoutes from './admin/dashboard.routes.js';
import userRoutes from './admin/user.routes.js';
import doctorRoutes from './admin/doctor.routes.js';
import childrenRoutes from './admin/children.routes.js';
import bookingRoutes from './admin/booking.routes.js';
import supportRoutes from './admin/support.routes.js';
import packagesRoutes from './admin/packages.routes.js';
import productsRoutes from './admin/products.routes.js';
import orderRoutes from './admin/order.routes.js';
import couponRoutes from './admin/coupon.routes.js';
import activityRoutes from './admin/activity.routes.js';
import paymentRoutes from './admin/payment.routes.js';
import walletRoutes from './admin/wallet.routes.js';
import reportsRoutes from './admin/reports.routes.js';
import pagesRoutes from './admin/pages.routes.js';
import settingsRoutes from './admin/settings.routes.js';
import onboardingRoutes from './admin/onboarding.routes.js';
import homeSlidersRoutes from './admin/home-sliders.routes.js';
import homeServicesRoutes from './admin/home-services.routes.js';
import homeArticlesRoutes from './admin/home-articles.routes.js';
import faqRoutes from './admin/faq.routes.js';
import notificationsRoutes from './admin/notifications.routes.js';
import bulkRoutes from './admin/bulk.routes.js';
import adminsRoutes from './admin/admins.routes.js';
import assessmentsRoutes from './admin/assessments.routes.js';
import maharaRoutes from './admin/mahara.routes.js';

const router = express.Router();

router.use('/auth', authRoutes);
router.use('/dashboard', dashboardRoutes);
router.use('/users', userRoutes);
router.use('/doctors', doctorRoutes);
router.use('/children', childrenRoutes);
router.use('/bookings', bookingRoutes);
router.use('/support', supportRoutes);
router.use('/packages', packagesRoutes);
router.use('/products', productsRoutes);
router.use('/orders', orderRoutes);
router.use('/coupons', couponRoutes);
router.use('/activity-logs', activityRoutes);
router.use('/', paymentRoutes);
router.use('/wallet', walletRoutes);
router.use('/reports', reportsRoutes);
router.use('/pages', pagesRoutes);
router.use('/settings', settingsRoutes);
router.use('/onboarding', onboardingRoutes);
router.use('/home-sliders', homeSlidersRoutes);
router.use('/home-services', homeServicesRoutes);
router.use('/home-articles', homeArticlesRoutes);
router.use('/faqs', faqRoutes);
router.use('/notifications', notificationsRoutes);
router.use('/bulk', bulkRoutes);
router.use('/admins', adminsRoutes);
router.use('/assessments', assessmentsRoutes);
router.use('/mahara', maharaRoutes);

export default router;
