ChildWithAssessments:
  allOf:
    - $ref: "#/components/schemas/Child"
    - type: object
      properties:
        assessmentResults:
          type: array
          items:
            $ref: "#/components/schemas/AssessmentResultDetail"
        helpAssessments:
          type: array
          items:
            allOf:
              - $ref: "#/components/schemas/HelpAssessmentSchema"
              - type: object
                properties:
                  doctor:
                    type: object
                    nullable: true
                    properties:
                      id:
                        type: string
                      name:
                        type: string
                      email:
                        type: string
                        format: email
                  assessmentResult:
                    allOf:
                      - $ref: "#/components/schemas/AssessmentResultDetail"
                    nullable: true
