UserSettings:
  type: object
  properties:
    id:
      type: string
      format: uuid
    username:
      type: string
      nullable: true
    fullName:
      type: string
      nullable: true
    email:
      type: string
      nullable: true
    phone:
      type: string
      nullable: true
    language:
      type: string
      example: ar
    allowPrivateMsg:
      type: boolean
    isAnonymous:
      type: boolean
    avatar:
      type: string
      nullable: true

UpdateUserSettingsRequest:
  type: object
  properties:
    fullName:
      type: string
    username:
      type: string
    email:
      type: string
      format: email
    language:
      type: string
      example: ar
    allowPrivateMsg:
      type: boolean
    isAnonymous:
      type: boolean
    avatar:
      type: string
      nullable: true

ChangePasswordRequest:
  type: object
  required: [currentPassword, newPassword]
  properties:
    currentPassword:
      type: string
      minLength: 6
    newPassword:
      type: string
      minLength: 6
